GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNIEZhZGlsIiwiZW1haWwiOiJtZjk1NTU3NThAZ21haWwuY29tIiwiaWF0IjoxNzU4MzcyMjg2LCJleHAiOjE3NTgzNzIzMDF9.EVSB0UphYWUDBIn3KjSKWAGh7ZuNfhOHOrsZM6k6V74

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"M Fadil",
    "email":"mf9555758@gmail.com",
    "password":"123456",
    "confPassword":"123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"mf9555758@gmail.com",
    "password":"123456"
}



###
GET http://localhost:5000/token